version: "2"

run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1

output:
  show-stats: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - asciicheck
    - errorlint
    - godot
    - gocritic
    - prealloc
    - gochecknoinits
    - revive
    - whitespace
    - unconvert
    - musttag
    - errname
    - reassign
    - usestdlibvars
    - mirror
    - loggercheck
    - durationcheck
    - asasalint
    - errchkjson
